### ISSUE TITLE
nginx, fluentd 用途及檢測方法

### ISSUE THREAD

**Issue by cwyu57** [srcmesh-workshop/kubernetes-adoption-hands-on#3]
Hi @life1347 

想請作業問題

先描述一下我目前理解的作業的整體架構

wordpress pod 跑起 wordpress container
  expose service type loadbalancer 對 外部使用者 提供服務
  透過 service 連線至 mysql   

mysql pod 跑 mysql container
  expose service type clusterip 對 cluster 內提供服務

目前為主的架構我可以利用 wordpress service 的 external ip 檢測
  wordpress 是否正確被建立 -> ok
  wordpress 對 mysql 的連線是否正常 -> ok

---

再加入 nginx 以及 fluentd 後
  nginx-fluentd pod 以 sidecar pattern 跑 nginx container 以及 fluentd container
  透過 service 連線到 wordpress

  目前的狀況是初步看 nginx-fluentd 的 nginx container 和 fluentd container 都有正確跑起來

  想請問 nginx 以及 fluentd 這兩個服務在整體架構的用途以及如何偵錯排查設定是否正確？

---

Environment: 
  kubernetes docker desktop v1.18.8

--- 

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql-pod
spec:
  containers:
    - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root-password
              name: mysql-secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mysql-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: mysql-database
              name: mysql-configmap
      image: mysql:5.6
      imagePullPolicy: IfNotPresent
      name: mysql
      ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
---
apiVersion: v1
data:
  mysql-database: test_database
kind: ConfigMap
metadata:
  name: mysql-configmap
---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
  root-password: cGFzc3dvcmQ=
  user: dXNlcg==
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      protocol: TCP
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress
  name: wordpress-pod
spec:
  containers:
    - env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: mysql-secret
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-secret
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: mysql-database
              name: mysql-configmap
      image: wordpress:latest
      imagePullPolicy: IfNotPresent
      name: wordpress
      ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: wordpress
  type: LoadBalancer
---
apiVersion: v1
data:
  nginx.conf: >+2
    
            user  nginx;
    worker_processes  1;


    error_log  /var/log/nginx/error.log warn;

    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        # Path to access.log & error.log
        access_log /var/log/nginx/pod-log-dir/access.log  main;
        error_log /var/log/nginx/pod-log-dir/error.log  warn;

        sendfile        on;
        keepalive_timeout  65;
        gzip  on;

        upstream backend {
            # must match the target service name
            server wordpress-service:80;
        }

        server {
            listen       80;
            location / {
                # $http_host is the host name that users seen on the browser URL
                # and it equals to `HTTP_HOST` request header.
                proxy_set_header Host $http_host;

                # You have to change this according to your setup.
                proxy_pass http://wordpress-service;

                # Modify `Location` of 301 or 302 HTTP response, so
                # that the browser will follow the correct location.
                proxy_redirect ~^http://[^/]*/(.*) http://$http_host/$1;
            }
        }
    }

kind: ConfigMap
metadata:
  name: nginx-configmap
---
apiVersion: v1
data:
  fluent.conf: >
    <source>
            type tail
            path /logs/**/access.log
            tag nginx.access
            format nginx
          </source>

          <source>
            @type tail
            format /^(?<time>d{4}/d{2}/d{2} d{2}:d{2}:d{2}) [(?<log_level>w+)] (?<pid>d+).(?<tid>d+): (?<message>.*)$/
            tag nginx.error
            path /logs/**/error.log
          </source>

          <match nginx.access>
            @type stdout
          </match>

          <match nginx.error>
            @type stdout
          </match>
kind: ConfigMap
metadata:
  name: fluentd-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          volumeMounts:
            - mountPath: /var/log/nginx/pod-log-dir
              name: log-volume
            - mountPath: /etc/nginx
              name: nginx-conf
        - image: fluentd:v1.9-1
          name: fluentd
          volumeMounts:
            - mountPath: /fluentd/etc
              name: fluentd-conf
      volumes:
        - emptyDir: {}
          name: log-volume
        - configMap:
            name: nginx-configmap
          name: nginx-conf
        - configMap:
            name: fluentd-configmap
          name: fluentd-conf
```

**Comment by life1347** [comment]
此次作業使用 Nginx 主要原因是其支援多種不同功能，比方說 request rewrite 與 HTTPs 支援，因為常作為對外的 proxy 服務。作業的 wordpress 其實可以替換成公司的任意服務，若公司的生產環境的服務想要直接對外，也是可以不需要 Nginx 的。

Fluentd 是用來收集 Nginx 的 access.log error.log 之用，因為此次沒有讓各位嘗試架設 ELK stack，因此是讓 fluentd 將讀到的 log 用 stdout 的方式印出來。

設定是否正確最簡單的方式就是確認服務是否都符合預期的運作 (db, log 是否正常)，常見偵錯的方式可以使用 `logs` 確認日誌是否符合預期或是 `port-forwarding` 將 Pod 的特定的 port 號導向至本機端，就可以在本機端進行測試 (可以參考 https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/ )

**Comment by life1347** [comment]
@cwyu57 well done!

基本上沒有太大問題，唯一的小 bug 是在 fluentd 的 log-volume 沒有掛載到

```yaml
        - image: fluentd:v1.9-1
          name: fluentd
          volumeMounts:
            - mountPath: /logs
              name: log-volume
            - mountPath: /fluentd/etc
              name: fluentd-conf
```

修改成這樣後兩個容器才會共享同個 log-volume
